spring:
  application:
    name: ${APP_NAME:tspringboot}

  datasource:
    url: jdbc:mysql://localhost:3306/tjava
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: "066311"
    hikari:
      auto-commit: false
      connection-timeout: 3000
      validation-timeout: 3000
      max-lifetime: 60000
      maximum-pool-size: 20
      minimum-idle: 1


